development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: mark@secondbureau.com
  :password: gege19821111
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: mark@secondbureau.com
  :password: gege19821111
  :enable_starttls_auto: true
