#!/usr/bin/env bash

heroku pgbackups:capture --app production-ouranos --expire
curl -o /tmp/production-ouranos-latest.dump `heroku pgbackups:url --app production-ouranos`
echo "drop database ouranos_development;" | psql
echo "create database ouranos_development;" | psql
pg_restore -O -d ouranos_development /tmp/production-ouranos-latest.dump

